[package]
name = "ranked_voting"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
#nanoserde = "0.1"
# todo remove
#itertools = "0.8"
sha256="1.0"
# TODO: use as fallback for the crypto mode
java-rand = "0.2"
