name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RCV_TEST_DIR: rcv/src/test/resources/network/brightspots/rcv/test_data

jobs:

  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install stable          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Clone the official repository of RCVTab
        uses: actions/checkout@v2
        with:
          repository: BrightSpots/rcv
          path: rcv
          ref: master

      - name: Test
        run: |
          cargo check
          cargo test

      - name: Build
        run: |
          cargo build --release

      - name: Test release
        run: |
          ./target/release/timrcv --data $RCV_TEST_DIR/2013_minneapolis_mayor_scale/2013_minneapolis_mayor_scale_config.json \
          --reference $RCV_TEST_DIR/2013_minneapolis_mayor_scale/2013_minneapolis_mayor_scale_expected_summary.json \
          --out /dev/null