name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          staging="timrcv-linux"
          mkdir -p "$staging"
          cargo build --all --release 
          strip target/release/timrcv 
          mv target/release/timrcv "$staging/"
          echo "Artifacts to be packaged:"
          echo $staging
          ls $staging/*
          tar czf "$staging.tar.gz" "$staging"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: timrcv-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
          staging="timrcv-windows"
          mkdir -p "$staging"
          cargo build --all --release 
          mv target/release/timrcv.exe "$staging/"
          echo "Artifacts to be packaged:"
          echo $staging
          ls $staging/*
          7z a "$staging.zip" "$staging"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: timrcv-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: |
          staging="timrcv-macos"
          mkdir -p "$staging"
          cargo build --all --release 
          strip target/release/timrcv 
          mv target/release/timrcv "$staging/"
          echo "Artifacts to be packaged:"
          echo $staging
          ls $staging/*
          tar czf "$staging.tar.gz" "$staging"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: timrcv-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
